project:
  type: website
  output-dir: docs

website:
  title: "myblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kavynabel
format:
  html:
    theme: sandstone
    # See this theme link, with more stuff it seems cooler haha
    css: styles.css



